version: "3"

services:
  web:
    restart: always
    build: .
    env_file:
      - ./settings/.env
      - ./settings/.env.cache
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - ./:/code/
    networks:
      - db_network
      - cache_network
    depends_on:
      - db
      - cache
    tty: true
    stdin_open: true
    container_name: django_app

  cache:
    restart: always
    image: redis:5
    networks:
      - cache_network
    ports:
      - 6379:6379
    container_name: redis

  db:
    restart: always
    image: postgres:latest
    # Exposed post for external connections
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - db_network
    env_file:
      - ./settings/.env.database
    volumes:
      - ./db_data:/var/lib/postgresql/data
    container_name: postgres_db

networks:
  db_network:
    driver: bridge
  cache_network:
    driver: bridge

volumes:
  db_data:
